### ISSUE TITLE
Remove Jishaku cog from help command

### ISSUE THREAD

**Issue by CypherGuy** [stshrewsburyDev/discord-better-help#7]
So I've recently been working with Jishaku, an experimental cog (docs here - https://jishaku.readthedocs.io/en/latest/cog.html#task-system), but when I run the help command, I can see Jishaku as part of it. Is there a way for me to disable certain cog from appearing in the help command, or if not, would it be possible to make such a system please? I have attached photos for your convenience.

(Page 6 of the picture)

<img width="419" alt="Screenshot 2021-05-28 at 13 23 50" src="https://user-images.githubusercontent.com/74025064/119983402-02651a00-bfb8-11eb-9e9a-29825a6b4aff.png">

<img width="518" alt="Screenshot 2021-05-28 at 13 23 55" src="https://user-images.githubusercontent.com/74025064/119983366-f6795800-bfb7-11eb-98dc-14b0f7f62e63.png">

**Comment by SkylaDev** [comment]
The jishaku module does have support for hiding itself from the help menus of a discord bot via its `jsk hide` and `jsk show` commands. Also only users with access to the jsk commands can see it in help menus due to how discord.py works so logically only you and other bot owners should see it there.

But if you wanted to auto hide it on startup so no one can see it I suggest doing something like this:
```python
# Load cog
bot.load_extension("jishaku")
# Auto hide Jishaku
bot.get_command("jishaku").hidden = True
```
Looking through the docs to jsk it seems this is the only way this is possible.

**Comment by CypherGuy** [comment]
Thank you very much, I'm not sure how I didn't see this earlier!

Also, the issue about removing cogs from your help command could still be an issue. What I mean is, say I didn't want the `owner` cog to show, as I didn't want anyone seeing what commands there are. Is there a way for me to disable that?

Thanks!

**Comment by SkylaDev** [comment]
> Also, the issue about removing cogs from your help command could still be an issue. What I mean is, say I didn't want the `owner` cog to show, as I didn't want anyone seeing what commands there are. Is there a way for me to disable that?

Only users with access to the commands within a cog can see them. I may add a feature in the future that will allow you to hide certain cogs based on their name/id but another simple fix for this is to add `hidden=True` to any command you dont wish to have appear in your help menu. (Eg: `@commands.command(name="example", hidden=True)`)

For example:

- me (the bot owner):
![image](https://user-images.githubusercontent.com/39103023/120012820-e7a29d80-bfd7-11eb-9734-523ca08a011c.png)

- Another user (not a bot owner), bot responds with nothing as there are no commands that the user has access to:
![image](https://user-images.githubusercontent.com/39103023/120012899-06a12f80-bfd8-11eb-9fdd-57b64e43725d.png)

**Comment by CypherGuy** [comment]
Thanks for letting me know about that, I'll come back if there's anything else!
