### ISSUE TITLE
Add first and last page reactions to help command

### ISSUE THREAD

**Issue by CypherGuy** [stshrewsburyDev/discord-better-help#8]
So I was wondering if it would be possible to make a feature where a user can click a reaction, similar to the first and last one on the attached image, and it will take you to the first or last page of your help command in your package? I've noticed it's used a lot and it's a nice feature to have. Thanks!
<img width="350" alt="Screenshot 2021-06-27 at 12 37 26" src="https://user-images.githubusercontent.com/74025064/123528542-f2884500-d6df-11eb-9b39-e4726212cd88.png">

**Comment by SkylaDev** [comment]
Sorry for super late response, I have this feature planned out and should be releasing it sometime later today or tomorrow.
After that I will most likely put all updates on hold until discord.py 2.0 is released as I presume it will require some larger updates as the module has changed quite a bit.

**Comment by SkylaDev** [comment]
Feature has now been implemented into version 1.3.0 which should now be public on the releases tab and on PyPi (pip)
https://pypi.org/project/discord-better-help/1.3.0/
